version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: 
          name: Install local magpylib
          command: pip install .
      - run: 
          name: Set up testing tools and environment
          command: mkdir test-results && pip install tox && pip install pylint
      - run:
          name: Run pylint test
          command: pylint --rcfile='./.pylintrc' magpylib
      - run:
          name: Run code test coverage suite
          command: tox
      
  deploy:
    docker:
      - image: python:3
    steps:
        - checkout
        - run:
            name: install python dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make dev
        - run:
            name: verify git tag vs. version
            command: |
              python3 -m venv venv
              . venv/bin/activate
              python setup.py verify
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username: magpylib" >> ~/.pypirc
              echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: create packages
            command: |
              make package
        - run:
            name: upload to pypi
            command: |
              . venv/bin/activate
              twine upload --repository pypi dist/*
